**Download** (right-click, save target as ...) this page as a jupyterlab notebook from: [Lab8-TH](http://54.243.252.9/engr-1330-webroot/8-Labs/Lab08/Lab08-TH.ipynb)

___

# <font color=darkred>Exercise Set 8: Matrices a Red Pill Approach </font>

**Medrano, Giovanni**

**R11521018**

ENGR 1330 ES 8 - Homework

In [1]:
# Preamble script block to identify host, user, and kernel
import sys
! hostname
! whoami
print(sys.executable)
print(sys.version)
print(sys.version_info)

DESKTOP-6HAS1BN
desktop-6has1bn\medra
C:\Users\medra\anaconda3\python.exe
3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)



___

## Reading Files


## Exercise 0 
Define the matrix A and the vector u in Python. Then perform all of the tasks below. 

\begin{gather}
\mathbf{A} =
\begin{pmatrix}
1 & 3 & 5 & 7 \\
2 & 4 & 6 & 8 \\
-3 & -2 & -1 & 0 \\
\end{pmatrix}
~ \mathbf{u} = 
\begin{pmatrix}
10 \\
20 \\
30 \\
\end{pmatrix}
\end{gather}

1. Print the matrix A
2. Print the vector u
3. Print the shape of A 
4. Print the shape of u
5. Print the first column of A
6. Print the first two rows of A
7. Print the first two entries of u
8. Print the last two entries of u
9. Print the bottom left 2×2 partition (submatrix) of A
10. Print the middle two elements of the middle row of A

---

Use the code blocks below to craft your answer.

In [12]:
#%reset -f # only if necessary

In [11]:
# read/create matrix A
import numpy as np
A = np.array([[1,3,5,7],[2,4,6,8],[-3,-2,-1,0]])
# read/create vector u
u = np.array([10,20,30])

# print A
print('This is matrix A')
print(A)
print('\n')
# print u
print('This is matrix B')
print(u)
print('\n')

# determine and Print the shape of A 
print('This is the shape of A')
print(A.shape)
print('\n')

# determine andPrint the shape of u
print('This is the shape of U')
print(u.shape)
print('\n')

# Print the first column of A
print('this is the first column of A')
for j in range(3):
    print(A[j][0])
print("\n")

# Print the first two rows of 
print('This is the first two rows of A')
print(A[0])
print(A[1])
print('\n')
# Print the first two entries of u

print('These are the first two entries of u.')
for j in range(2):
    print(u[j])
print('\n')
# Print the last two entries of u
print('These are the last two entries of u')
print(u[1:])
print('\n')

# Print the bottom left 2×2 partition (submatrix) of A
print('These are the bottom left 2x2 submatrix of A')
for j in range(1,3):
    print(A[j][0:2])
print('\n')
# Print the middle two elements of the middle row of A
print('These are the middle two elements of the middle row of A')
print(A[1][1:3])

This is matrix A
[[ 1  3  5  7]
 [ 2  4  6  8]
 [-3 -2 -1  0]]


This is matrix B
[10 20 30]


This is the shape of A
(3, 4)


This is the shape of U
(3,)


this is the first column of A
1
2
-3


This is the first two rows of A
[1 3 5 7]
[2 4 6 8]


These are the first two entries of u.
10
20


These are the last two entries of u
[20 30]


These are the bottom left 2x2 submatrix of A
[2 4]
[-3 -2]


These are the middle two elements of the middle row of A
[4 6]


## Exercise 1

Use your script to multiply two matrices, just like in the Lab (in-Lab portion).
Apply the script to find $\mathbf{A}\mathbf{B}$ where.

\begin{gather}
\mathbf{A} =
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
5 & 6  \\
\end{pmatrix}
~~~~ \mathbf{B} = 
\begin{pmatrix}
7 & 8 & 9 \\
10 & 11 & 12 \\
\end{pmatrix}
\end{gather}

The two matrices are located in files:

[http://54.243.252.9/engr-1330-webroot/8-Labs/Lab08/Amat.txt](http://54.243.252.9/engr-1330-webroot/8-Labs/Lab08/Amat.txt)

and:

[http://54.243.252.9/engr-1330-webroot/8-Labs/Lab08/Bmat.txt](http://54.243.252.9/engr-1330-webroot/8-Labs/Lab08/Bmat.txt)

You should download these files before proceeding

In [18]:
# read file Amat.txt
fileOne = open("amat.txt",'r')
# read file Bmat.txt
fileTwo = open('bmat.txt','r')
# create a destination matrix ABmatrix
lineOne = fileOne.readlines()
lineTwo = fileTwo.readlines()
print(lineOne)
A = []
B = []
# print Amat
for i in lineOne:
    l=i.strip('\n')
    l=l.split(',')
    l=list(map(int,l))
    A.append(l)
for i in lineTwo:
    l=i.strip('\n')
    l=l.split(',')
    l=list(map(int,l))
    B.append(l)    
# print Bmat
# perform the multiplication put the result into ABmatrix 

final = [[0 for j in range(len(B[0]))]for i in range(len(A))]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            final[i][j] += A[i][k] * B[k][j]
print(final)
# print ABmatrix

['1,2\n', '3,4\n', '5,6']
[[27, 30, 33], [61, 68, 75], [95, 106, 117]]


___

## References

1. A linear algebra primer [https://numericalmethodssullivan.github.io/ch-linearalgebra.html](https://numericalmethodssullivan.github.io/ch-linearalgebra.html)

3. Python file manipulations [https://www.tutorialspoint.com/python/python_files_io.htm](https://www.tutorialspoint.com/python/python_files_io.htm)

2. A Complete Beginners Guide to Matrix Multiplication for Data Science with Python Numpy [https://towardsdatascience.com/a-complete-beginners-guide-to-matrix-multiplication-for-data-science-with-python-numpy-9274ecfc1dc6](https://towardsdatascience.com/a-complete-beginners-guide-to-matrix-multiplication-for-data-science-with-python-numpy-9274ecfc1dc6)

